projectname    GumPrimitives

srcdir         src
exampledir     examples

findlibraries  SELF GumEssentials GumSystem GumMaths
headerfiles    gum-primitives Primitives/
examples       

extralibraries_begin
extralibraries_end

extraincludepaths_begin
extraincludepaths_end


customstr_begin
customstr_end

tocombinetargets_begin
tocombinetargets_end